# Deep Learning

![nlp](https://wrm5sysfkg-flywheel.netdna-ssl.com/wp-content/uploads/2019/01/NLP-Technology-in-Healthcare.jpg)

# Introduction

Section goals:
- Understand basic overview of Deep Learning
- Understand basics of LSTM and RNN
- Use LSTM to generate text from source corpus 
- Create QA Chatbots with Python

# 8.1.0 The basic Perceptron Model

Artificial neural networks or ANN's have a basis in biology. A Perceptron is the common term for an artificial neuron that mimics a biological neuron.

The biological neuron is made up of component parts: 
- Dendrites
- Body
- Axon

The artificial neuron is also multipart: 
- Inputs
- Body
- Output

# 8.2.0 Keras

In [29]:
import numpy as np

In [30]:
from sklearn.datasets import load_iris

In [31]:
iris = load_iris()

In [32]:
x = iris.data

In [33]:
y = iris.target

In [34]:
from keras.utils import to_categorical

In [35]:
y = to_categorical(y)

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=42)

In [38]:
from sklearn.preprocessing import MinMaxScaler

In [39]:
scaler = MinMaxScaler()

In [40]:
scaler.fit(x_train)

MinMaxScaler()

In [41]:
scaled_x_train = scaler.transform(x_train)

In [42]:
scaled_x_test = scaler.transform(x_test)

In [43]:
from keras.models import Sequential
from keras.layers import Dense

In [44]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [45]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.fit(scaled_x_train, y_train, epochs=200, verbose=2)

Epoch 1/200
 - 1s - loss: 1.1543 - accuracy: 0.3000
Epoch 2/200
 - 0s - loss: 1.1474 - accuracy: 0.3000
Epoch 3/200
 - 0s - loss: 1.1415 - accuracy: 0.3100
Epoch 4/200
 - 0s - loss: 1.1355 - accuracy: 0.3200
Epoch 5/200
 - 0s - loss: 1.1290 - accuracy: 0.3200
Epoch 6/200
 - 0s - loss: 1.1228 - accuracy: 0.3200
Epoch 7/200
 - 0s - loss: 1.1177 - accuracy: 0.3200
Epoch 8/200
 - 0s - loss: 1.1128 - accuracy: 0.3200
Epoch 9/200
 - 0s - loss: 1.1083 - accuracy: 0.3400
Epoch 10/200
 - 0s - loss: 1.1039 - accuracy: 0.3600
Epoch 11/200
 - 0s - loss: 1.0993 - accuracy: 0.3500
Epoch 12/200
 - 0s - loss: 1.0954 - accuracy: 0.3600
Epoch 13/200
 - 0s - loss: 1.0913 - accuracy: 0.3800
Epoch 14/200
 - 0s - loss: 1.0871 - accuracy: 0.3800
Epoch 15/200
 - 0s - loss: 1.0841 - accuracy: 0.4000
Epoch 16/200
 - 0s - loss: 1.0802 - accuracy: 0.3900
Epoch 17/200
 - 0s - loss: 1.0770 - accuracy: 0.3900
Epoch 18/200
 - 0s - loss: 1.0736 - accuracy: 0.4000
Epoch 19/200
 - 0s - loss: 1.0702 - accuracy: 0.4100
Ep

In [47]:
model.predict(scaled_x_test)

array([[6.46506203e-03, 6.57006800e-01, 3.36528093e-01],
       [9.71322954e-01, 2.84389425e-02, 2.38171298e-04],
       [2.81957318e-06, 5.48888147e-02, 9.45108354e-01],
       [4.88138339e-03, 6.34165525e-01, 3.60953093e-01],
       [1.08065910e-03, 4.24147785e-01, 5.74771523e-01],
       [9.55046833e-01, 4.44088355e-02, 5.44341747e-04],
       [4.82193977e-02, 8.23449790e-01, 1.28330842e-01],
       [5.31006153e-05, 1.68322966e-01, 8.31623852e-01],
       [9.44099447e-04, 3.18148047e-01, 6.80907905e-01],
       [2.09649596e-02, 7.73502707e-01, 2.05532342e-01],
       [3.93887254e-04, 3.52640182e-01, 6.46965921e-01],
       [9.63348567e-01, 3.60602252e-02, 5.91216958e-04],
       [9.74746764e-01, 2.50020996e-02, 2.51196208e-04],
       [9.66157794e-01, 3.33341695e-02, 5.07981807e-04],
       [9.87617075e-01, 1.22843934e-02, 9.85338265e-05],
       [3.89748579e-03, 6.60716176e-01, 3.35386276e-01],
       [3.94649978e-05, 1.44074813e-01, 8.55885684e-01],
       [2.58401204e-02, 7.68771

In [48]:
model.predict_classes(scaled_x_test)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [49]:
preds = model.predict_classes(scaled_x_test)

In [50]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [51]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [52]:
confusion_matrix(y_test.argmax(axis=1), preds)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]])

In [54]:
print(classification_report(y_test.argmax(axis=1), preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [55]:
accuracy_score(y_test.argmax(axis=1), preds)

0.96

In [56]:
model.save('iris_Classifier.h5')